n1=input("enter first number :")
n2=input("enter second number:")
add=int(n1)+int(n2)
diff=int(n1)-int(n2)
pro=int(n1)*int(n2)
div=int(n1)/int(n2)
print("add=",add)
print("diff=",diff)
print("pro=",pro)
print("div=",div)

